/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/ui/BaseButton.vue')['default']
    BaseInput: typeof import('./components/ui/BaseInput.vue')['default']
    BaseSelect: typeof import('./components/ui/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./components/ui/BaseTextarea.vue')['default']
    CategoryManager: typeof import('./components/settings/CategoryManager.vue')['default']
    CreateSaleModal: typeof import('./components/sales/CreateSaleModal.vue')['default']
    CustomerDetailModal: typeof import('./components/customers/CustomerDetailModal.vue')['default']
    CustomerFormModal: typeof import('./components/customers/CustomerFormModal.vue')['default']
    CustomerListTable: typeof import('./components/customers/CustomerListTable.vue')['default']
    CustomerStatusFilter: typeof import('./components/customers/CustomerStatusFilter.vue')['default']
    DashboardCustomizeModal: typeof import('./components/dashboard/DashboardCustomizeModal.vue')['default']
    DashboardHeader: typeof import('./components/DashboardHeader.vue')['default']
    DashboardOrderDetailModal: typeof import('./components/dashboard/DashboardOrderDetailModal.vue')['default']
    DashboardWidget: typeof import('./components/dashboard/DashboardWidget.vue')['default']
    ExpenseFormModal: typeof import('./components/finance/ExpenseFormModal.vue')['default']
    ExpenseListTable: typeof import('./components/finance/ExpenseListTable.vue')['default']
    ExpenseTab: typeof import('./components/finance/tabs/ExpenseTab.vue')['default']
    FinanceFormModal: typeof import('./components/finance/FinanceFormModal.vue')['default']
    FinanceListTable: typeof import('./components/finance/FinanceListTable.vue')['default']
    FinanceSummaryCards: typeof import('./components/finance/FinanceSummaryCards.vue')['default']
    ImageLightbox: typeof import('./components/common/ImageLightbox.vue')['default']
    IncomeModal: typeof import('./components/finance/IncomeModal.vue')['default']
    IncomeTab: typeof import('./components/finance/tabs/IncomeTab.vue')['default']
    Logo: typeof import('./components/common/Logo.vue')['default']
    OrderListTable: typeof import('./components/orders/OrderListTable.vue')['default']
    PaymentFormModal: typeof import('./components/payments/PaymentFormModal.vue')['default']
    PaymentListTable: typeof import('./components/payments/PaymentListTable.vue')['default']
    PaymentModal: typeof import('./components/sales/PaymentModal.vue')['default']
    ProductFormModal: typeof import('./components/products/ProductFormModal.vue')['default']
    ProductImageUpload: typeof import('./components/products/ProductImageUpload.vue')['default']
    ProductListTab: typeof import('./components/products/tabs/ProductListTab.vue')['default']
    ProductStockInput: typeof import('./components/products/ProductStockInput.vue')['default']
    ProductTable: typeof import('./components/products/ProductTable.vue')['default']
    PurchaseFormModal: typeof import('./components/purchases/PurchaseFormModal.vue')['default']
    PurchaseListTab: typeof import('./components/products/tabs/PurchaseListTab.vue')['default']
    PurchaseListTable: typeof import('./components/purchases/PurchaseListTable.vue')['default']
    PurchaseSearchInput: typeof import('./components/purchases/PurchaseSearchInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleCustomerSelect: typeof import('./components/sales/partials/SaleCustomerSelect.vue')['default']
    SaleExpensesPanel: typeof import('./components/sales/partials/SaleExpensesPanel.vue')['default']
    SaleItemsTable: typeof import('./components/sales/partials/SaleItemsTable.vue')['default']
    SaleListTable: typeof import('./components/sales/SaleListTable.vue')['default']
    SalesListTable: typeof import('./components/orders/SalesListTable.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SmartExpenseInput: typeof import('./components/sales/partials/SmartExpenseInput.vue')['default']
  }
}
